<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>Dalton Spillman</Authors>
    <Company />
    <Product />
    <PackageProjectUrl>https://github.com/daltonks/SignalR-Protobuf</PackageProjectUrl>
    <RepositoryUrl>https://github.com/daltonks/SignalR-Protobuf</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>protobuf signalr</PackageTags>
    <Version>2.0.1</Version>
    <PackageReleaseNotes>Target .NET 10; update SignalR and Google.Protobuf dependencies</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.35.1" />
    <PackageReference Include="Grpc.Tools" Version="2.82.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="**/*.proto" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="models.proto" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Update="models.proto" GrpcServices="None" Access="Internal" />
  </ItemGroup>


</Project>
